.coveragerc
.landscape.yaml
.travis.yml
README.md
defender/config.py
defender/data.py
defender/decorators.py
defender/tasks.py
defender/test_settings.py
defender/tests.py
defender/travis_settings.py
defender/utils.py
setup.py

Added an optional way to write the login's to the database. Instead of writing them inline, it can be done via a celery task. This will make the login even faster since it won't have to wait for the database write.
There is a new config ``DEFENDER_USE_CELERY`` which lets the application know if you want to use the celery tasks or not.
I had to move some stuff around to get it to work correctly.

Add Celery option for writing to database

---

.travis.yml
README.md
defender/models.py
defender/tests.py
setup.py

This PR ended up being bigger than I expected as I think something fishy was happening due to the pinning of the django==1.6.8.
* This PR limits suport to Django version 1.6.x and 1.7.x.
* Add a couple of things related to running Django 1.7
* Better support for python3
fixes #16

Support django 1.6 and django 1.7

---

defender/connection.py
defender/tests.py

Use a mocked instance of redis outside tests so it can be used it
on django projects tests.

Allow redis connections to be mocked outside tests

---

defender/test.py
defender/tests.py

Provide TransactionTestCase and TestCase that clear the defender cache between runs.
That should allow users of defender to easier integrate defender with their projects.
Note: There's a bit of duplication between DefenderTestCaseTest and DefenderTransactionTestCaseTest. That's on purpose as I am not a big fan of two many dependencies between test cases.
@kencochrane What do you think?

Provide helper TestCases to be used with Defender

---

.travis.yml
README.md
defender/admin.py
defender/config.py
defender/connection.py
defender/management/commands/cleanup_django_axes.py
defender/tests.py
defender/urls.py
defender/utils.py
defender/views.py
setup.py

This is a PR to fix issues #15 #35 and #36 
- Bumped version to 0.3
- Bumped Django versions on travis tests
- updated README.md
- Added management command ``cleanup_django_axes`` to clean up access
attempt table.
- Added ``DEFENDER_STORE_ACCESS_ATTEMPTS`` config to say if you want to
store attempts to DB or not.
- Added ``DEFENDER_ACCESS_ATTEMPT_EXPIRATION`` config to specify how long
to store the access attempt records in the db, before the management command
cleans them up.
- changed the Django admin page to remove some filters which were making the
page load slow with lots of login attempts in the database.

Add management command

---

README.md
defender/config.py
defender/tests.py
defender/utils.py

Allow username and IP to be mutually exclusive when performing lockouts.  This resolves an issue where you may have many users behind a single IP (common amongst our enterprise customers) where 1 user forgetting their password will lock out their peers.
The setting changes the lockout checks to evaluate if the IP failure limit *and* the username failure limit has been reached before issuing the lockout.
Any suggestions or comments are more than welcome!

User and ip lockout

---

.travis.yml
CHANGES
README.md
defender/config.py
defender/tests.py
defender/utils.py
setup.py

I added the ability to disable the IP locking features, when enabled it will only lock out based on username. 
This would be useful if you have a lot of users that connect via the same proxy, and you want to prevent everyone from getting locked out because of one user's bad login attempts.
I also updated the travisCI settings, to test for newer versions of Django and python 3.5
bumped version to 0.4.0
/cc @bcwalrus @marcusmartins

Added  DEFENDER_DISABLE_IP_LOCKOUT so that you can disable IP lockouts if you want

---

defender/tasks.py
defender/tests.py
defender/utils.py

The `is_already_locked` method assumes how the username is stored in the
request. This patch adds helpers that don't to allow for more flexible
implementation.
/cc: @kencochrane @marcusmartins @fxdgear
*Note*: I'll also push this to `dockerhub/django-defender` master and do a release from there.

Add helpers that do not assume how to retrieve `username`

---

.travis.yml
defender/test_settings.py
defender/test_urls.py
defender/tests.py
defender/travis_settings.py
defender/utils.py
defender/views.py
setup.py

- Django 1.9 is supported in installation requirements (setup.py)
- Use url method instead of patterns for urlpatterns in test URLs setup
- Fix testing of failed login redirect to URL for Django 1.9 and above (LOCKOUT_URL)

Django 1.9 support

---

defender/urls.py

As of Django 1.8, creating `urlpatterns` with the `django.conf.urls.patterns` function became deprecated and will be [removed in 1.10.](https://docs.djangoproject.com/en/1.8/ref/urls/#patterns).
Note: this may not work with Django 1.6, so if that still needs to be supported some additional testing may be needed.

making urlpatterns a plain list

---

defender/utils.py

A watched login failure causes a 500 saving a 256 character long username into the login attempts.  Conditionally slice it to fit AccessAttempt

Fix DataError on login

---

defender/admin.py

removing the django admin filter for username, when you have a lot of records, it will prevent the admin page from displaying, and causes it to be really slow otherwise.

removing the django admin filter for username

---

README.md
defender/config.py
defender/tests.py
defender/utils.py

I added the ability to disable the username locking features, when enabled it will only lock out based on IP. 
This would be useful if blocking users is unacceptable. An attacker can bruteforce with username wordlist - block all accounts from that list and stop operability all system.

Add disable username block feature

---

defender/config.py
defender/utils.py

- Every function which loads username from request has the optional paramter: get_username
piggyback:
- removed redefinition of USERNAME_FORM_FIELD from defender.config

[#70] get username from request is more flexible

---

defender/test_urls.py
defender/tests.py
defender/urls.py

This fixes bug #76 where an exception like
```
Reverse for 'defender_unblock_username_view' with arguments '(u'user+test@domain.tld',)' and keyword arguments '{}' not found. 1 pattern(s) tried: [u'admin/defender/blocks/username/(?P[A-Za-z0-9-._@]+)/unblock$']
```
was raised when trying to access the `/admin/defender/blocks/` URL when a user with a plus sign had been locked out.

Allow usernames with plus signs in unblock view

---

README.md

Doc: `BasicAuthenticationDefender` should precede other auth classes

---

.travis.yml
README.md
defender/decorators.py
defender/middleware.py

- Update middleware to work with Django 1.11 and older versions.
- Add Django 1.11 to the Travis test matrix.
- Update README to remove mention to Django 1.11 not being supported.
- Avoid repeated patching using a middleware class-level flag instead of checking function names.
Resolves #78.

Add support for Django 1.11

---

.travis.yml
README.md
defender/config.py
defender/connection.py
defender/tests.py
defender/travis_settings.py
setup.py

The idea is to avoid rewriting the Redis URL on the defender settings, since probably you already have it on your django `CACHES` settings.
Pending:

Taking redis client from django.core.cache

---

.coveragerc
.travis.yml
defender/decorators.py
defender/middleware.py
defender/tests.py
setup.py

@kencochrane as discussed in #85

Allow decoration of functions beyond the admin login

---

defender/admin.py
defender/config.py
defender/connection.py
defender/exampleapp/settings.py
defender/management/commands/cleanup_django_defender.py
defender/middleware.py
defender/migrations/0001_initial.py
defender/models.py
defender/south_migrations/0001_initial.py
defender/test_settings.py
defender/tests.py
defender/travis_settings.py
defender/utils.py

This is just a quick code cleanup to remove some of the warnings from the linters, things got a little dirty lately, so we needed to do some spring cleaning.
Signed-off-by: Ken Cochrane <kencochrane@gmail.com>

Cleanup the code to remove lint warnings

---

defender/middleware.py

#92 Fixes the `TypeError: object.__init__() takes no parameters` that happens with the new MIDDLEWARE that is new in django 1.10

Middleware fix for django >= 1.10

---

CHANGES
README.md
setup.py

Bump version to 0.5.1
0.5.1
=====
- Middleware fix for django >= 1.10 #93 [@Temeez]
- Force the username to lowercase #90 [@MattBlack85]
Signed-off-by: Ken Cochrane <kencochrane@gmail.com>

Bump version to 0.5.1

---

CHANGES
defender/tests.py
defender/urls.py

The reason why we need to handle almost all special symbols is in cases when username is like 'some!username'
Issue: #76

Update regex for 'unblock_username_view'.

---

setup.py

hiredis isn't needed to run this app, therefore it doesn't need to be required by `setup.py`

removing hiredis dependency in setup.py

---

defender/connection.py

When using the `django_redis.cache.RedisCache` cache the defender is unable to get the raw client successfully. This fixes the issue by using the `client` property and then the `get_client` method to return the raw redis client.

Correctly get raw client when using django_redis cache.

---

CHANGES
README.md
defender/connection.py
setup.py

This PR replaces #115 which moves the mockredis requirement to a test requirement from an install requirement.
Signed-off-by: Ken Cochrane <KenCochrane@gmail.com>

Move mockredis to test requirements. 

---

defender/connection.py

This is a simple change that allows defender to connect to a secure ElastiCache redis instance (aka rediss://)
Future work could include allowing proxy connections using certificates to traditional Redis instances.

Added ssl option when instantiating StrictRedis

---

CHANGES
README.md
defender/config.py
defender/decorators.py
defender/exampleapp/settings.py
defender/exampleapp/utils.py
defender/tests.py
defender/utils.py

This setting allow to override default `get_username_from_request` function.
In my case there was a need to strip username on login attempt. The username stripping is done in in custom Authentication backend. I do username stripping in authentication for better user experience.
If I will not do username stripping - there will be possibility to brute password for user. For example: Attacker can use username that contains spaces in login form, then spaces will be trimmed by auth. backend, but not by defender. So attacker will get possibility to brute user passwords without account locking by defender.

Add possibility to use custom `utils.get_username_from_request` function

---

setup.py

Kombu 4.4 requires redispy 3.2.0 and seems to [fix celery stability issues](https://github.com/celery/kombu/issues/1016), bumping the version should just work according to ["Upgrading from redis-py 2.X to 3.0"](https://pypi.org/project/redis/)

redispy 3.2.0 compat

---

.travis.yml
defender/travis_settings.py
setup.py

We've been using latest djang-defender with Django 2.2 since its release and it's been working without any issues that we've seen. We just get annoying pip warnings about it not being officially supported.

Add and test support for Django 2.2

---

setup.py

Added support for redis client 3.2.1

---

defender/tests.py
defender/utils.py

Only send the username/IP blocked signal if the user/IP is actually blocked.
Like this multiple sending of the signal is avoid. The block is set even though to avoid race conditions. There is still a slight chance the signal is send twice, but that should be OK.

send user/ip blocked signal only once

---

docs/Makefile
docs/conf.py
docs/index.rst

This adds the initial Sphinx shims so that Read the Docs can generate a documentation site.
Further setup is required for the actual content, this PR only aims to setup correct infrastructure for building the docs.
Fixes #139 
Relates #138

Initial Read the Docs Sphinx shims

---

defender/models.py
setup.py

Updated to allow this app to work with Django 3.x by removing reference to python 2 specific code without breaking backwards compatibility (i.e. usable with Django < 2 with python 2.x).
- Django dependency in setup.py may need to be limited to <= 3.1
- Django-redis module updated to something more contemporary - don't know why it was previously limited but so far seems to work fine.
Currently testing this in a full async Django install (Nginx + daphne + websockets enabled), but tbh the site in question does not yet use a lot of the async capability; some are planned. The currently staged/beta app seems to work and passes all unittests.

Update for django 3.x

---

README.rst
defender/config.py
defender/connection.py
defender/tests.py

if the special character in redis password, such like '@'
my password is 'calmkart#@!'
i set the DEFENDER_REDIS_URL to 'redis://:calmkart#@!@localhost:6379/0', but the password 'calmkart#@!' cant be well supported.
so we add a new param DEFENDER_REDIS_PASSWORD_QUOTE, default is `False`. But if we have special character in our redis password, we can change the redis password to `urllib.quote_plus('calmkart#@!')` and set the DEFENDER_REDIS_PASSWORD_QUOTE to `True`
```
DEFENDER_REDIS_URL = "redis://:calmkart%23%40%21@localhost:6379/0"
DEFENDER_REDIS_PASSWORD_QUOTE = True
```
This will enable support for special characters in redis passwords.
This update will not have any impact on the past usage environment. The code that is already in use does not require any configuration changes. This …

FIX: support for special character in redis password(such like '@')

---

README.rst

Just a simple refactor in the code sample
The function [utils.check_request](https://github.com/jazzband/django-defender/blob/71312eb841b3843838b3a135f46d61067b9a8602/defender/utils.py#L347) in fact not just check if the attempt count has reached its limit but also and mainly it **records** or **resets** the failed attempt count in Redis. The real good refactor in the future I think would be to rename this function to something like `add_or_reset_failled_attempts`.
So for now I just did 3 little refactors here:
1. Added a comment to explain what the function really does as its name is not so clear yet 
2. Removed the variable `user_not_blocked` because in the code sample it is redundant with the `login_unsuccessful` variable. The user only gets blocked when the login is unsuccessful, so …

Update sample code in README

---

defender/tasks.py

Using django-defender with any other project that uses `autodiscover_modules` tasks,  makes django-defender depend on celery.
To give you an example, I have a Django project with Huey (https://github.com/coleifer/huey) and I need this PR to use django-defender.
I think this solves the comment
> not sure how to get this to look better. ideally we want to dynamically apply the celery decorator based on the USE_CELERY setting.

dynamic load celery

---

requirements.txt

The django-redis-cache version 2.1.3 is broken in pypi, let's roll back to 2.1.1 until it is fixed.

Fix Django-redis-cache version

---

defender/connection.py

The `password_quote` is treated as optional inside the function.
It shouldn't fail if not passed

FIX: make password quote optional in the funciton signature

---

defender/__init__.py

The last tag is [v0.8.0](https://github.com/jazzband/django-defender/releases/tag/v0.8.0)
It missed in last release

Fix version.

---

CHANGES.rst
README.rst
defender/config.py
defender/signals.py
tox.ini

Fixes #184 
Tox tests are currently failing for `djmain` (Django 4.0) environment because of deprecated/removed items (see issue #184 for full details).  
This PR fixes those issues, by:
- replacing `ugettext_lazy()` with `gettext_lazy()` (for which it is an alias)
- removing the no longer supported `providing_args` argument when defining Signals.  
The PR also fixes a minor typo in the 'tox.ini` file
Note, the commented out `providing_args` were left in for reference, but can be completely removed if required.

Fix failing tests to work with Django (4.0) main dev branch

---

defender/tests.py
defender/utils.py

patching https://github.com/jazzband/django-defender/issues/188, first committing changes to test that should fail, then will squash with fixing changes

Fix for IP backdoor to DEFENDER_LOCK_OUT_BY_IP_AND_USERNAME

---

defender/apps.py

This patch removes a warning but also prevents creating migrations in projects
where DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField".
This is a fix for https://github.com/jazzband/django-defender/issues/195

Define AppConfig.default_auto_field to match the initial migration

---

exampleapp/settings.py
exampleapp/urls.py

The exampleapp is still running deprecated code.

Update `exampleapp` to use new routing/templates settings

---

.github/workflows/test.yml

This is a workaround due to [SQLite version bug on PyPy v7.3.8](https://foss.heptapod.net/pypy/pypy/-/issues/3690).
Reference:https://github.com/actions/setup-python/issues/339#issuecomment-1050840703

Pinpoint PyPy version

---

README.rst

The correct way to add django admin urls is without using `include()` https://docs.djangoproject.com/en/4.0/ref/contrib/admin/#hooking-adminsite-to-urlconf

Fix admin url example docs

---

.github/workflows/test.yml

Revert #206.
PyPy 7.3.9 has now been [released](https://doc.pypy.org/en/latest/release-v7.3.9.html) with the updated SQLite version.

Revert PyPy version pinpoint

---

defender/connection.py

When setting DEFENDER_REDIS_URL, add capability to use non-default username.

add username option to redis config

---

README.rst
exampleapp/urls.py

if  `/admin/` comes before `/admin/defender/` then `/admin/defender/blocks/` url will give 404

Changing order of defender urls in documentation and exampleapp/urls.py

---

README.rst
defender/tests.py
defender/utils.py
exampleapp/urls.py

When the IP is an ipv6, like `::ffff:192.168.24.24`, `strip_keys` method gives an incorrect response.

Bugfix strip_keys

---

defender/data.py

Use `timezone.now` instead of `datetime.now` when constructing datetime objects. `timezone.now` ensures the timezone-awareness to be consistent with `settings.USE_TZ`

Replace datetime.now with timezone.now

---

tox.ini

Not sure what the current plans are for supporting Python 3.11 and/or Django 4.2, but testing on them would be a good start.

Test on Django 4.2 and Python 3.11

---

defender/connection.py
defender/tests.py

The custom method defined here has no real advantage
- the redis lib implements it better and have support for many use cases
- maintaining this implementation is error-prone and unnecessary work for overworked open-source contributors :)
Especially, when you want to pass query parameters here, they are not supported (for eg a custom certificate authority)

Use redis parse_url method instead of a custom one

---

defender/decorators.py
defender/tests.py
defender/utils.py

Previously using of custom `get_username` function with disabled IP lockout caused unhandled exception
`Exception("Invalid state requested")`

Fix `watch_login` with custom username

---

README.rst

Suggesting that this uses the name of the _client_ is misleading and confusing, as that would be the name of a backend (e.g. RedisCache). The referencing code uses DEFENDER_REDIS_NAME to look up the named cache from `CACHES` instead.

Update DEFENDER_REDIS_NAME documentation

---

defender/templates/admin/defender/app_index.html

[django-defender's `app_index.html` template](https://github.com/jazzband/django-defender/blob/v0.9.7/defender/templates/admin/defender/app_index.html) is based on some old version of Django's `app_index.html` template. It's just like [the one used in many versions of Django prior to 3.1](https://github.com/django/django/blob/3.0.14/django/contrib/admin/templates/admin/app_index.html) except that its indentation is different and it doesn't contain `{% block bodyclass %}{{ block.super }} app-{{ app_label }}{% endblock %}`. This has worked fine for anyone not relying on the `bodyclass` block being present. However, as of Django 4.2.1, the breadcrumbs are handled differently (compare [Django 4.2's `app_index.html` template](https://github.com/django/django/blob/4.2/django/contrib/admin/templa …

Updated app_index.html

---

defender/templates/defender/admin/blocks.html
defender/views.py

This is useful for things such as a customized `site_title` and/or `site_header`, for example.

Improved the "Blocked Logins" page's admin integration
