defender/tests.py
setup.py

Fixes local testing with no redis running

Fixed redis mocking in tests

---

defender/utils.py

Gets rid of both TODOs I was able to find.
https://github.com/andymccurdy/redis-py#pipelines

Use pipelines for atomic transactions

---

.coveragerc
README.md
defender/migrations/0001_initial.py
defender/south_migrations/0001_initial.py

Add database migrations for Django 1.7 and Django 1.6 using South.
South >= 1.0 is required so we can provide support for Django 1.7 and 1.6
Fixes #14

Add Migrations

---

defender/tests.py
defender/utils.py

Simplify the is_already_locked code and make sure
that we're testing that code better.
The test are more explicit around blocks by username and ip to be able to catch regression bugs better.
closes #20

refactor is_already_locked and add better test coverage

---

README.md
defender/config.py
defender/middleware.py
defender/test_settings.py
defender/tests.py
defender/travis_settings.py

cleaned up a little remove the ViewDecoratorMiddleware
/cc @marcusmartins @shin- please review.

cleaned up a little remove the ViewDecoratorMiddleware

---

setup.py

Won't start up without mockredis installed.

Add dependency on mockredis

---

defender/tests.py
defender/utils.py

Converts from bytes to string using .decode('utf-8')

Make key_list read from redis Python 3 compatible

---

.travis.yml

updated the TravisCI settings to
- remove pypy
- updated django versions

updated travisCI settings

---

README.md
defender/templates/defender/lockout.html

- sample authentication method described in README
piggyback:
- typo in lockout.html

Example djangorestframework auth method

---

CHANGES
README.md
setup.py

Getting ready for release 0.5.0
Thank you @dukebody, @Franr, @MattBlack85
Signed-off-by: Ken Cochrane <kencochrane@gmail.com>

Release 0.5.0

---

setup.py

Fix the django install)requires version in setup.py so that it allows versions of django 1.11.x
fixes #97

change django install_requires version

---

defender/tests.py
defender/utils.py

In my case, having to provide a `get_username_from_request` callback is very redudant (currently I just provide a `lambda _: username`). Would be nice to be able to just pass the `username` directly.

utils: add username kwarg for providing username directly rather than via callback arg

---

README.md

README: align reverse-proxy settings

---

.travis.yml
defender/exampleapp/settings.py
defender/test_settings.py
defender/test_urls.py
defender/travis_settings.py
setup.py

* remove Python 3.3
* remove Django 1.8-1.10
* add Celery v4
* update travis config
* update admin URL

Feature update Python and Django versions

---

README.md

No other changes to code or other parts of README.md

added new site to list of sites using Defender

---

defender/signals.py
defender/tests.py
defender/utils.py

Add signals send when a username or an ip is unblocked.

Add unblock signals

---

defender/admin.py
defender/config.py
defender/connection.py
defender/data.py
defender/decorators.py
defender/exampleapp/settings.py
defender/exampleapp/urls.py
defender/management/commands/cleanup_django_defender.py
defender/middleware.py
defender/migrations/0001_initial.py
defender/models.py
defender/signals.py
defender/south_migrations/0001_initial.py
defender/tasks.py
defender/test.py
defender/test_settings.py
defender/test_urls.py
defender/tests.py
defender/travis_settings.py
defender/urls.py
defender/utils.py
defender/views.py
docs/conf.py
setup.py

Run black with Python 2.7 as target version to unify the code styling and make it more linter and style guide compliant.
This is mostly a stylistic change but is one that I've made for multiple projects to ease the maintenance with higher similarity.
This will create a suspiciously large contribution in the GitHub graph so it would be  nice to let a bot do this instead.

PEP8 formatting

---

.travis.yml
README.rst
defender/__init__.py
docs/conf.py
requirements.txt
setup.py
tox.ini

Refs https://github.com/jazzband-roadies/help/issues/174.

Add Tox config and prepare for project releases.

---

CHANGES.rst
defender/__init__.py

Getting ready for 0.7.0 release

Added changes for release 0.7.0

---

setup.py

Fix redis requirement

---

.github/workflows/test.yml
CHANGES.rst
README.rst
defender/ci_settings.py
defender/test_settings.py
setup.py
tox.ini

- Drop Django 3.1 support.
- Confirm support for Django 4.0
- Confirm support for Python 3.10

Update python django

---

README.rst

Fix nested list in DEFENDER_LOCKOUT_TEMPLATE

---

README.rst

Show an example of how to adapt Django Defender for preventing brute-force submissions against the password-reset view.
- Logs submissions against the email address, instead of the default username, because email address is the only thing always available for the whole process.
- From: https://github.com/jazzband/django-defender/issues/204

Update README with password reset example

---

CHANGES.rst

I noticed that the current PyPI version has outdated package version specifiers and updating a new version to the PyPI repository could be a fairly small task :)

Version 0.9.2

---

defender/tests.py
defender/utils.py

See issue #213 for context. This pull request adds a `strip_port_number` function to utils, and calls it from `get_ip` if `BEHIND_REVERSE_PROXY = True`

Strip port number from IP address in X-Forwarded-For (resolves #213)

---

CHANGES.rst
README.rst
defender/config.py
defender/data.py
defender/test_settings.py
defender/tests.py
defender/utils.py
requirements.txt

This addresses changes based on the discussion here https://github.com/jazzband/django-defender/issues/223

Add new config options and update logic/tests to account for them
